<?php
session_start();require_once __DIR__.'/../../config.php';require_once __DIR__.'/../includes/helpers.php';if(!isset($_SESSION['staff_id'])){header('Location: ../../auth/staff_login.php');exit();}$staff_id=(int)$_SESSION['staff_id'];$stmt=$conn->prepare('SELECT * FROM staff WHERE staff_id=?');$stmt->execute([$staff_id]);$staff=$stmt->fetch(PDO::FETCH_ASSOC);if(!$staff){session_destroy();header('Location: ../../auth/staff_login.php');exit();}
$states=['Johor','Kedah','Kelantan','Melaka','Negeri Sembilan','Pahang','Penang','Perak','Perlis','Sabah','Sarawak','Selangor','Terengganu','Kuala Lumpur','Putrajaya','Labuan'];
if(isset($_POST['update_profile'])){
    $name=trim($_POST['staff_name']??'');$email=trim($_POST['staff_email']??'');$phone=trim($_POST['staff_phonenum']??'');$dob=$_POST['staff_dob']??'';$state=$_POST['staff_state']??'';$gender=(int)($_POST['staff_gender']??0);
    $stmt=$conn->prepare('SELECT staff_id FROM staff WHERE staff_email=? AND staff_id<>?');$stmt->execute([$email,$staff_id]);
    if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)){$_SESSION['error']='Enter a valid name and email.';}
    elseif($stmt->fetch()){$_SESSION['error']='That email is already used by another staff account.';}
    else{
        $image=$staff['staff_image']?:'uploads/default.png';
        if(isset($_FILES['staff_image']) && $_FILES['staff_image']['error']!==UPLOAD_ERR_NO_FILE){
            if($_FILES['staff_image']['error']!==UPLOAD_ERR_OK || $_FILES['staff_image']['size']>2000000){$_SESSION['error']='Profile image must be below 2 MB.';header('Location: update_profile.php');exit();}
            $ext=strtolower(pathinfo($_FILES['staff_image']['name'],PATHINFO_EXTENSION));$allowed=['jpg','jpeg','png','webp'];
            if(!in_array($ext,$allowed,true)){$_SESSION['error']='Use JPG, JPEG, PNG or WEBP for the profile image.';header('Location: update_profile.php');exit();}
            $folder=__DIR__.'/../../images/uploads/staff/';if(!is_dir($folder))mkdir($folder,0777,true);$filename='staff_'.$staff_id.'_'.time().'.'.$ext;
            if(!move_uploaded_file($_FILES['staff_image']['tmp_name'],$folder.$filename)){$_SESSION['error']='The profile image could not be saved.';header('Location: update_profile.php');exit();}$image='uploads/staff/'.$filename;
        }
        $stmt=$conn->prepare('UPDATE staff SET staff_name=?,staff_email=?,staff_phonenum=?,staff_dob=?,staff_state=?,staff_gender=?,staff_image=? WHERE staff_id=?');$stmt->execute([$name,$email,$phone,$dob,$state,$gender,$image,$staff_id]);$_SESSION['staff_name']=$name;$_SESSION['success']='Profile updated successfully.';
    }
    header('Location: update_profile.php');exit();
}
$root_prefix='../../';$page_title='Profile';include __DIR__.'/../includes/head.php';
?>
<style>
.profile-layout{display:grid;grid-template-columns:330px 1fr;gap:14px}.identity-card{position:sticky;top:112px;align-self:start;padding:24px;text-align:center}.avatar-wrap{position:relative;width:132px;height:132px;margin:2px auto 18px}.avatar-wrap img{width:100%;height:100%;border-radius:50%;object-fit:cover;border:5px solid var(--staff-surface-solid);box-shadow:0 0 0 1px var(--staff-border),var(--staff-shadow-soft)}.avatar-badge{position:absolute;right:4px;bottom:6px;width:36px;height:36px;display:grid;place-items:center;border:3px solid var(--staff-surface-solid);border-radius:50%;background:var(--staff-blue);color:#fff}.identity-card h2{margin:0;font-size:1.25rem;letter-spacing:-.03em}.identity-card .role{display:inline-flex;margin-top:7px;padding:5px 9px;border-radius:999px;background:var(--staff-blue-soft);color:var(--staff-blue);font-size:.7rem;font-weight:850}.identity-meta{display:grid;gap:8px;margin-top:20px;text-align:left}.identity-meta div{display:flex;align-items:center;gap:9px;padding:10px 11px;border-radius:14px;background:var(--staff-surface-2);color:var(--staff-muted);font-size:.72rem}.profile-form{padding:22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.span-2{grid-column:1/-1}.upload-zone{display:flex;align-items:center;gap:14px;padding:14px;border:1px dashed var(--staff-border);border-radius:17px;background:var(--staff-surface-2)}.upload-zone img{width:54px;height:54px;border-radius:50%;object-fit:cover}.upload-zone input{max-width:100%}.form-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px;padding-top:18px;border-top:1px solid var(--staff-border)}
@media(max-width:850px){.profile-layout{grid-template-columns:1fr}.identity-card{position:static}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}}
</style>
</head><body class="staff-body"><?php include __DIR__.'/../includes/header.php';?><?php if(kcw_admin_role($staff['staff_job'])) include __DIR__.'/../includes/admin_toolbar.php';?>
<main class="staff-main"><div class="staff-page-heading"><div><span class="staff-eyebrow"><i class="fa-solid fa-user"></i> Account</span><h1>Your profile</h1><p>Keep your contact details and staff photo accurate.</p></div><a class="ios-btn ios-btn-secondary" href="change_password.php"><i class="fa-solid fa-lock"></i> Change password</a></div>
<section class="profile-layout"><aside class="ios-card identity-card"><div class="avatar-wrap"><img src="<?= kcw_h(kcw_staff_image_url($staff,$root_prefix)) ?>" alt="Profile photo" id="profilePreview" onerror="this.src='../../images/uploads/default.png'"><span class="avatar-badge"><i class="fa-solid fa-camera"></i></span></div><h2><?= kcw_h($staff['staff_name']) ?></h2><span class="role"><?= kcw_h($staff['staff_job']) ?></span><div class="identity-meta"><div><i class="fa-solid fa-envelope"></i><?= kcw_h($staff['staff_email']?:'No email') ?></div><div><i class="fa-solid fa-calendar-check"></i>Joined <?= date('d M Y',strtotime($staff['staff_hiredate'])) ?></div><div><i class="fa-solid fa-location-dot"></i><?= kcw_h($staff['staff_state']) ?></div></div></aside>
<article class="ios-card profile-form"><form method="POST" enctype="multipart/form-data"><div class="form-grid"><div class="ios-field span-2"><label>Profile photo</label><div class="upload-zone"><img src="<?= kcw_h(kcw_staff_image_url($staff,$root_prefix)) ?>" alt="Preview" data-upload-preview onerror="this.src='../../images/uploads/default.png'"><div><input type="file" name="staff_image" accept="image/jpeg,image/png,image/webp" data-file-preview="[data-upload-preview]"><div class="ios-helper">JPG, PNG or WEBP · maximum 2 MB</div></div></div></div><div class="ios-field"><label>Full name</label><input class="ios-input" name="staff_name" value="<?= kcw_h($staff['staff_name']) ?>" required></div><div class="ios-field"><label>Email</label><input class="ios-input" type="email" name="staff_email" value="<?= kcw_h($staff['staff_email']) ?>" required></div><div class="ios-field"><label>Phone number</label><input class="ios-input" name="staff_phonenum" inputmode="numeric" value="<?= kcw_h($staff['staff_phonenum']) ?>" required><span class="ios-helper">The current database stores phone numbers as an integer.</span></div><div class="ios-field"><label>Date of birth</label><input class="ios-input" type="date" name="staff_dob" value="<?= kcw_h($staff['staff_dob']) ?>" required></div><div class="ios-field"><label>State</label><select class="ios-select" name="staff_state" required><?php foreach($states as $s):?><option <?= $staff['staff_state']===$s?'selected':'' ?>><?= kcw_h($s) ?></option><?php endforeach;?></select></div><div class="ios-field"><label>Gender</label><select class="ios-select" name="staff_gender"><option value="0" <?= (int)$staff['staff_gender']===0?'selected':'' ?>>Male</option><option value="1" <?= (int)$staff['staff_gender']===1?'selected':'' ?>>Female</option></select></div></div><div class="form-actions"><a class="ios-btn ios-btn-secondary" href="../staff_home.php">Cancel</a><button class="ios-btn ios-btn-primary" name="update_profile"><i class="fa-solid fa-check"></i> Save changes</button></div></form></article></section>
</main><?php include __DIR__.'/../includes/footer.php';?></body></html>
